// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OZr1-MHrxh5YpCvjDxYNmkC_P-PMFSE',
    appId: '1:872679716506:web:db52b1a973382cb13e1123',
    messagingSenderId: '872679716506',
    projectId: 'food-truck-19f2d',
    authDomain: 'food-truck-19f2d.firebaseapp.com',
    storageBucket: 'food-truck-19f2d.appspot.com',
    measurementId: 'G-V3FQMY8FMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiQtYk36PXyRmOh281VGfL4p7GkRYztk',
    appId: '1:872679716506:android:539f0b41960cd1193e1123',
    messagingSenderId: '872679716506',
    projectId: 'food-truck-19f2d',
    storageBucket: 'food-truck-19f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg_ejeVxSlwdunF7buywXDr0_CtefY1Xk',
    appId: '1:872679716506:ios:b03b0205779b5e063e1123',
    messagingSenderId: '872679716506',
    projectId: 'food-truck-19f2d',
    storageBucket: 'food-truck-19f2d.appspot.com',
    iosBundleId: 'com.example.foodTruck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg_ejeVxSlwdunF7buywXDr0_CtefY1Xk',
    appId: '1:872679716506:ios:b03b0205779b5e063e1123',
    messagingSenderId: '872679716506',
    projectId: 'food-truck-19f2d',
    storageBucket: 'food-truck-19f2d.appspot.com',
    iosBundleId: 'com.example.foodTruck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OZr1-MHrxh5YpCvjDxYNmkC_P-PMFSE',
    appId: '1:872679716506:web:aaf208ae40b5e3893e1123',
    messagingSenderId: '872679716506',
    projectId: 'food-truck-19f2d',
    authDomain: 'food-truck-19f2d.firebaseapp.com',
    storageBucket: 'food-truck-19f2d.appspot.com',
    measurementId: 'G-7SYLHDEFB7',
  );
}
